parameters:
  app.type.custom_type.class: CustomExtendedChoiceBundle\Form\Type\CustomType
  app.repository.language.class: AppBundle\Repository\LanguageRepository
  app.repository.treatment.class: AppBundle\Repository\TreatmentRepository

services:
  app.repository.language:
    class: %app.repository.language.class%
    lazy: true

  app.repository.treatment:
    class: %app.repository.treatment.class%
    lazy: true

  app.type.language:
    class: %app.type.custom_type.class%
    arguments: [@app.repository.language, 'language']
    tags:
      - {name: form.type, alias: 'language'}

  app.type.treatment:
    class: %app.type.custom_type.class%
    arguments: [@app.repository.treatment, 'treatment']
    tags:
      - {name: form.type, alias: 'treatment'}

